<?php

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5c8128a09694b',
        'title' => 'Area Information',
        'fields' => array(
            array(
                'key' => 'field_56c4bf004d2e4',
                'label' => 'Main Photo',
                'name' => 'main_photo',
                'type' => 'image_crop',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'crop_type' => 'hard',
                'target_size' => 'custom',
                'width' => 1024,
                'height' => 500,
                'preview_size' => 'full',
                'force_crop' => 'yes',
                'save_in_media_library' => 'no',
                'retina_mode' => 'no',
                'save_format' => 'object',
                'library' => 'all',
            ),
            array(
                'key' => 'field_56c4c00b4d2e5',
                'label' => 'TripAdvisor Embed',
                'name' => 'tripadvisor_embed',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'area-info.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5c8128a09cca8',
        'title' => 'Big Buttons',
        'fields' => array(
            array(
                'key' => 'field_56ba1d1f7f59e',
                'label' => 'Button One Photo',
                'name' => 'button_one_photo',
                'type' => 'image_crop',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'crop_type' => 'hard',
                'target_size' => 'custom',
                'width' => 250,
                'height' => 250,
                'preview_size' => 'thumbnail',
                'force_crop' => 'yes',
                'save_in_media_library' => 'yes',
                'retina_mode' => 'no',
                'save_format' => 'object',
                'library' => 'all',
            ),
            array(
                'key' => 'field_56ba1db27f5a1',
                'label' => 'Button One Label',
                'name' => 'button_one_label',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_56ba1df07f5a4',
                'label' => 'Button One Link',
                'name' => 'button_one_link',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_56ba1d8e7f59f',
                'label' => 'Button Two Photo',
                'name' => 'button_two_photo',
                'type' => 'image_crop',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'crop_type' => 'hard',
                'target_size' => 'custom',
                'width' => 250,
                'height' => 250,
                'preview_size' => 'thumbnail',
                'force_crop' => 'yes',
                'save_in_media_library' => 'yes',
                'retina_mode' => 'no',
                'save_format' => 'object',
                'library' => 'all',
            ),
            array(
                'key' => 'field_56ba1dbc7f5a2',
                'label' => 'Button Two Label',
                'name' => 'button_two_label',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_56ba1e217f5a6',
                'label' => 'Button Two Link',
                'name' => 'button_two_link',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_56ba1d9b7f5a0',
                'label' => 'Button Three Photo',
                'name' => 'button_three_photo',
                'type' => 'image_crop',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'crop_type' => 'hard',
                'target_size' => 'custom',
                'width' => 250,
                'height' => 250,
                'preview_size' => 'thumbnail',
                'force_crop' => 'yes',
                'save_in_media_library' => 'yes',
                'retina_mode' => 'no',
                'save_format' => 'object',
                'library' => 'all',
            ),
            array(
                'key' => 'field_56ba1dd27f5a3',
                'label' => 'Button Three Label',
                'name' => 'button_three_label',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_56ba1e2c7f5a7',
                'label' => 'Button Three Link',
                'name' => 'button_three_link',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5cae4b5decbbb',
                'label' => 'Button Four Photo',
                'name' => 'button_four_photo',
                'type' => 'image_crop',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'crop_type' => 'hard',
                'target_size' => 'custom',
                'width' => 250,
                'height' => 250,
                'preview_size' => 'thumbnail',
                'force_crop' => 'yes',
                'save_in_media_library' => 'yes',
                'retina_mode' => 'no',
                'save_format' => 'object',
                'library' => 'all',
            ),
            array(
                'key' => 'field_5cae4b79ecbbc',
                'label' => 'Button Four Label',
                'name' => 'button_four_label',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5cae4b9becbbd',
                'label' => 'Button Four Link',
                'name' => 'button_four_link',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '5',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'excerpt',
            1 => 'discussion',
            2 => 'comments',
            3 => 'author',
            4 => 'format',
            5 => 'featured_image',
            6 => 'categories',
            7 => 'tags',
            8 => 'send-trackbacks',
        ),
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5c8128a0b4527',
        'title' => 'Testimonial / Review Info',
        'fields' => array(
            array(
                'key' => 'field_56c34d10f906a',
                'label' => 'Author',
                'name' => 'author',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_56c34d18f906b',
                'label' => 'Star Rating',
                'name' => 'star_rating',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_56c34d26f906c',
                'label' => 'Source',
                'name' => 'source',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'testimonial',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'permalink',
        ),
        'active' => true,
        'description' => '',
    ));
    
    endif;

?>